name: fitness_app
description: A Flutter fitness UI application with three screens.
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.3.0
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.0.0 # For app version and build number
  device_info_plus: ^10.1.0 # For device model, OS version
  uuid: ^4.4.0 # To generate unique session IDs
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_pdfview: ^1.4.0
  image_picker: ^1.1.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_commons:
  circular_buffer: ^0.12.0
  native_device_orientation: ^1.1.0

  camera: any
  provider: any
  permission_handler: any
  tflite_flutter: any
  image: any
  video_thumbnail: ^0.5.3
  open_file: ^3.3.2
  path_provider: ^2.1.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

flutter:
  uses-material-design: true

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-VariableFont_wght.ttf
        - asset: assets/fonts/LeagueSpartan-Medium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartan-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
          weight: 700

  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/icons/close.svg
    - assets/models/3.tflite
    - assets/golf.jpg
    - assets/gym.jpg
    - assets/laufen.jpg
    - assets/tennis.png
    - assets/videos/
    - assets/videos/gym/Dumbbell-Lateral-Raises.mov
    - assets/videos/planks/planks.mov
    - assets/videos/lunges/lunges.mov
    - assets/videos/running/running.mov
    - assets/images/thumbnail/thumbnail-running.jpeg
    - assets/images/thumbnail/thumbnail-dumbbell-lateral-raises.jpeg
    - assets/images/thumbnail/thumbnail-planks.jpeg
    - assets/images/thumbnail/thumbnail-lunges.jpeg
  generate: true
