#!/bin/bash
# ==============================================================================
# Initial Setup Script for the Flutter Project
# ==============================================================================
#
# This script performs the following steps:
# 1. Checks if the 'pre-commit' CLI tool is globally installed.
# 2. Checks if the '.pre-commit-config.yaml' file exists.
# 3. Checks if Git hooks are already installed for this repository.
# 4. If not, installs the hooks via 'pre-commit install'.
#
# Usage:
#   Run this script from the project root:
#     ./setup.sh
# ==============================================================================

# --- Colors for nicer output ---
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting initial project setup...${NC}"
echo "-------------------------------------------------"

# --- Step 1: Check if 'pre-commit' is available ---
echo "1. Checking if 'pre-commit' is installed..."
if ! command -v pre-commit &> /dev/null; then
  echo -e "${RED}Error: 'pre-commit' not found in PATH.${NC}"
  echo "The 'pre-commit' package is required for Git hooks."
  echo "Please install it globally, e.g.:"
  echo -e "${YELLOW}  pip install pre-commit${NC}"
  echo "or on macOS using:"
  echo -e "${YELLOW}  brew install pre-commit${NC}"
  exit 1
fi
echo -e "${GREEN}✓ 'pre-commit' is available.${NC}\n"

# --- Step 2: Check if config file exists ---
echo "2. Checking for '.pre-commit-config.yaml'..."
if [ ! -f ".pre-commit-config.yaml" ]; then
  echo -e "${RED}Error: Config file '.pre-commit-config.yaml' not found.${NC}"
  echo "Make sure you're running this script from the project root,"
  echo "and that the config file is present in the repository."
  exit 1
fi
echo -e "${GREEN}✓ Config file found.${NC}\n"

# --- Step 3: Check if hooks are installed ---
echo "3. Checking if pre-commit hooks are installed..."
HOOK_FILE=".git/hooks/pre-commit"
if [ -f "$HOOK_FILE" ] &&
   grep -q "Generated by pre-commit" "$HOOK_FILE"; then
  echo -e "${GREEN}✓ Pre-commit hooks are already installed. Nothing to do.${NC}"
  echo "-------------------------------------------------"
  echo -e "${GREEN}Setup completed successfully!${NC}"
  exit 0
fi
echo -e "${YELLOW}Hooks not installed yet. Proceeding with installation...${NC}\n"

# --- Step 4: Install hooks ---
echo "4. Installing pre-commit hooks..."
if ! pre-commit install; then
  echo -e "${RED}Error installing hooks with 'pre-commit install'.${NC}"
  echo "Please check the error above and try again."
  exit 1
fi

echo "-------------------------------------------------"
echo -e "${GREEN}✓ Setup completed successfully! Pre-commit hooks are now active.${NC}"
echo "On your next 'git commit', the checks will run automatically."

exit 0
